version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: base-nestjs-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: base-nestjs
    volumes:
      - base-nestjs-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: base-nestjs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - base-nestjs-pgadmin:/var/lib/pgadmin/data
    depends_on:
      - postgres

volumes:
  base-nestjs-postgres:
  base-nestjs-pgadmin:
